Add Russian LuCI translation and procd watchdog
- po/ru/olcrtc.po: Russian translation for luci-app-olcrtc (auto-built
  as luci-i18n-olcrtc-ru by luci.mk)
- olcrtc-watchdog.sh: periodic HTTP probe through own SOCKS5; restarts
  olcrtc service after N consecutive failures
- olcrtc.init: new 'watchdog' procd instance; +curl dependency
- olcrtc.config: new 'watchdog' section
- luci-app-olcrtc: watchdog form section in client.js
- CI: also build and ship luci-i18n-olcrtc-ru

diff --git a/olcrtc/files/olcrtc.init b/olcrtc/files/olcrtc.init
--- a/olcrtc/files/olcrtc.init
+++ b/olcrtc/files/olcrtc.init
@@ -7,6 +7,7 @@ STOP=10
 
 NAME=olcrtc
 PROG=/usr/bin/olcrtc
+WATCHDOG=/usr/libexec/olcrtc-watchdog.sh
 
 append_opt() {
 	local val="$2"
@@ -117,9 +118,45 @@ start_instance() {
 	procd_close_instance
 }
 
+start_watchdog() {
+	local cfg="$1"
+	local enabled probe_url interval timeout max_fails
+	local socks_host socks_port socks_user socks_pass
+
+	config_get_bool enabled "$cfg" enabled 0
+	[ "$enabled" = "1" ] || return 0
+
+	config_get probe_url "$cfg" probe_url 'https://www.google.com/generate_204'
+	config_get interval  "$cfg" interval  30
+	config_get timeout   "$cfg" timeout   10
+	config_get max_fails "$cfg" max_fails 3
+
+	# берём SOCKS-параметры из основной секции olcrtc/main
+	config_get socks_host main socks_host 127.0.0.1
+	config_get socks_port main socks_port 8808
+	config_get socks_user main socks_user
+	config_get socks_pass main socks_pass
+
+	[ -x "$WATCHDOG" ] || {
+		logger -t olcrtc "watchdog script $WATCHDOG missing or not executable"
+		return 1
+	}
+
+	procd_open_instance "watchdog"
+	procd_set_param command "$WATCHDOG" \
+		"$socks_host" "$socks_port" "$socks_user" "$socks_pass" \
+		"$probe_url" "$interval" "$timeout" "$max_fails"
+	procd_set_param respawn 3600 5 0
+	procd_set_param stdout 1
+	procd_set_param stderr 1
+	procd_set_param file /etc/config/olcrtc
+	procd_close_instance
+}
+
 start_service() {
 	config_load olcrtc
 	config_foreach start_instance olcrtc
+	config_foreach start_watchdog watchdog
 }
 
 service_triggers() {
